# Generated by Django 4.0.5 on 2022-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Назва')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('sort_num', models.IntegerField(verbose_name='Номер сортування')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Назва')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Опис')),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
                ('experience', models.IntegerField(verbose_name='Досвід роботи')),
                ('sort_num', models.IntegerField(verbose_name='Номер сортування')),
                ('directions', models.ManyToManyField(to='api.direction', verbose_name='Напрямки')),
            ],
        ),
    ]
