# Generated by Django 4.0.5 on 2022-06-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_direction_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='sort_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='directions',
            field=models.ManyToManyField(to='api.direction'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sort_num',
            field=models.IntegerField(),
        ),
    ]
