version: "3"

services:
  db:
    image: mysql:8
    restart: always
    env_file:
      - ./.env.db
    ports:
      - "3306:3306"
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    entrypoint: '/app/entrypoint.sh'
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - 'db'

